version: '3.12'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /mnt/Unlimited/Media/Shared:/mnt/media-volume
    environment:
      - UPLOAD_FOLDER=/mnt/media-volume
